### ISSUE TITLE
Barometer Cal Seems to Get Stuck

### ISSUE THREAD

**Issue by superjax** [rosflight/firmware#259]
So, it seems to me that if the barometer fails on the first try, it can never succeed.  Not sure why, but it seems to be a problem.

**Comment by wynn4** [comment]
![baro_calibrate_1_min](https://user-images.githubusercontent.com/21351818/31524283-b72539cc-af75-11e7-9dfe-e735d00efef1.png)

![screenshot from 2017-10-12 17-37-11](https://user-images.githubusercontent.com/21351818/31524202-4e71190a-af75-11e7-872e-10d531a174d8.png)
Also having this problem both with the flip32+ (with integrated baro) and with the flip32 (external baro).  It seems to happen on both, but more frequently with the external baro.  Below are some screen grabs of it happening on the flip32+ with onboard baro.  I didn't tell it to calibrate here, it just suddenly dove to a huge negative altitude.

![screenshot from 2017-10-12 17-35-51](https://user-images.githubusercontent.com/21351818/31524191-46dac2ae-af75-11e7-8642-0fbd65c7ea22.png)

Here I ran a rosservice call to calibrate the baro and it finally completed the calibration a minute later.  The whole time, the board was motionless so the "too much movement" thing wasn't due to the board actually moving or the pressure changing.

![calibrate_took_1_min](https://user-images.githubusercontent.com/21351818/31524280-b33cffde-af75-11e7-9f8c-235ab5f496d3.png)

**Comment by superjax** [comment]
Yeah, we need to find a way to replicate this on the ground.  I'll dig into the i2c driver and see if there's still some issues there.

**Comment by wynn4** [comment]
Great. The problem seems to be fairly easily replicated in my experience. The plots above were both from a plain flip32 at my desk with nothing else connected to it.

**Comment by superjax** [comment]
I just slowed down the barometer update a little bit, and am not leveraging the i2c queue as heavily.  Perhaps this will fix it.  @wynn4, can you confirm this fix on your hardware?  (`fix_259` branch)

**Comment by superjax** [comment]
As an unrelated, but potentially useful fix, I just recently added support for the BMP280 barometer from the rev6 naze32.  This chip uses far less overhead on the i2c lines.  It might be be a little better about avoiding this issue.

**Comment by superjax** [comment]
This was merged into master (illegally)
