### ISSUE TITLE
Throttle controlled by companion computer when in Manual mode

### ISSUE THREAD

**Issue by drinkdhmo** [rosflight/firmware#312]
MAV type: fixedwing

With the auto/manual switch in the manual position, the companion computer was still able to control the throttle.

**Comment by dpkoch** [comment]
The attitude and throttle overrides can be mapped to different switches by setting the `RC_ATT_OVRD_CHN` and `RC_THR_OVRD_CHN` parameters. The first thing to check is if your parameter configuration has these set to different channels, and if so set them to the same channel to get the behavior you want. If they were set to different channels and you were still seeing this behavior, then this is a bug.

For reference, this is documented [here](http://docs.rosflight.org/en/latest/user-guide/rc-configuration/#safety-pilot-configuration), and referenced [here](http://docs.rosflight.org/en/latest/user-guide/overview/#arming-errors-failsafe). If we can improve the documentation to make this more obvious, that would be great too.

**Comment by superjax** [comment]
I am just following up on this.  Was this actually the issue with the switch being twisted upside down?  @BillThePlatypus

**Comment by BillThePlatypus** [comment]
Yes, it was

**Comment by dpkoch** [comment]
So this was an issue with the actual transmitter hardware, not the firmware. Can we close this issue then?

**Comment by BillThePlatypus** [comment]
Yes, that would be fine

On Nov 8, 2018 5:31 PM, "Daniel Koch" <notifications@github.com> wrote:

So this was an issue with the actual transmitter hardware, not the
firmware. Can we close this issue then?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/rosflight/firmware/issues/312#issuecomment-437207032>,
or mute the thread
