### ISSUE TITLE
params are silently overwritten - add warning message

### ISSUE THREAD

**Issue by plusk01** [rosflight/firmware#342]
The firmware currently silently rewrites the parameters in EEPROM if [`Params::read()`](https://github.com/rosflight/firmware/blob/master/src/param.cpp#L270) returns false, based on the following logic:

```c++
bool Params::read(void)
{
  if (!RF_.board_.memory_read(&params, sizeof(params_t)))
    return false;

  if (params.version != GIT_VERSION_HASH)
    return false;

  if (params.size != sizeof(params_t) || params.magic_be != 0xBE || params.magic_ef != 0xEF)
    return false;

  if (compute_checksum() != params.chk)
    return false;

  return true;
}
```

The current philosophy is that we don't want to fly with corrupted params. Also, we don't want to fly with stale params from previous versions.

I agree with this, but I think the fact that parameters are overwritten **silently** is a problem.

Can we add a `ROSFLIGHT_WARNING_*` mavlink/enum? These do not require an action like errors do.

This came out of parameters being overwritten in SIL with no explanation.

**Comment by superjax** [comment]
ah, yeah, that's a good point.  I'm totally on board with throwing an error message.

While that will solve the SIL problem, making that error message show up in hardware is a bit tricker.  We currently don't have a mechanism for a sort of 'latched' error message.  Because the parameters get loaded up right away, any error message that gets sent will likely be missed by `rosflight_io` in hardware unless it were rebooted in software.

Anyway, I have no problems throwing an error message here, that makes a ton of sense.  It just brings up the idea of persistent information messages from bootup that we are not handling very well.
